### 
GET http://localhost:8383

### Test dashboard website
GET http://localhost:8383/dashboard

### 
GET http://localhost:8383/api/data

###
POST http://localhost:8383/api/data
Content-Type: application/json

{
    "name": "gilgamesh"
}


###
DELETE http://localhost:8383/api/data